<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>BlazorGE.Input</Title>
    <Description>BlazorGE (Game Engine) is a lightweight Blazor game engine/framework created by Aventius and other contributors (see Git repo)</Description>
    <PackageProjectUrl>https://github.com/mccabe93/BlazorGE/tree/net10</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mccabe93/BlazorGE/tree/net10</RepositoryUrl>
    <PackageTags>Blazor,aspnetcore,game-development,game-engine,game-framework,game,development,engine,framework,canvas</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>10.0.0.0</Version>
    <Company>Aventius,others</Company>
    <Authors>Aventius,others</Authors>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>
</Project>
